package org.dsa.strings;

/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 */
public class FindTheDifference {

    public static char getAddedChar(String s, String t) {
        int i = 0;
        int sum = 0;

        while (i < s.length()) {
            sum = sum + t.charAt(i) - s.charAt(i);
            i++;
        }

        sum = sum + t.charAt(i);

        return (char) sum;
    }

    public static void main(String[] args) {
        System.out.println(getAddedChar("abcd", "abcde"));
    }
}
